apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::160885270181:role/gh-actions-role
      username: github-ci
      groups:
        - system:masters
    - rolearn: arn:aws:iam::160885270181:role/gh-actions-role
      username: gh-actions
      groups:
        - system:masters